# https://taskfile.dev

version: "3"
dotenv: [".env", ".env.example", "{{.HOME}}/.env"]

includes:
  env:
    taskfile: .taskfile/env.yml
    optional: true
    flatten: true

  cmd:
    taskfile: .taskfile/cmd.yml
    optional: true

  git:
    taskfile: .taskfile/git.yml
    optional: true

  go:
    taskfile: .taskfile/go.yml
    optional: true
