package completion

import (
	"io"
)

func generateBashCompletion(w io.Writer) error {
	script := `#!/bin/bash
# mc-metrics bash completion script
# Generated by: mc-metrics completion bash

_mc_metrics_completions() {
    local cur prev words cword
    if type _init_completion &>/dev/null; then
        _init_completion || return
    else
        COMPREPLY=()
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
        words=("${COMP_WORDS[@]}")
        cword=$COMP_CWORD
    fi

    # 全局 flags
    local global_flags="--config -c --server-url --server-path-prefix --server-timeout \
        --auth-type --auth-user --auth-password --auth-token \
        --tls-ca --tls-cert --tls-key --tls-skip-verify --help -h"

    # 主命令
    local main_commands="query q export e import i version completion help"

    # query 子命令和 flags
    local query_commands="metrics labels label-values series version"
    local query_flags="--output-format -o --output-no-headers --time --range --step"

    # export 子命令和 flags
    local export_commands="json csv native version"
    local export_flags="--start --end --output -o --gzip"
    local export_json_flags="--max-rows-per-line"
    local export_csv_flags="--csv-format --reduce-mem-usage"

    # import 子命令和 flags
    local import_commands="json csv native prometheus version"
    local import_flags="--input -i --gzip"
    local import_prometheus_flags="--job --instance"

    # completion 子命令
    local completion_commands="bash zsh"

    # 处理 flag 值补全
    case "$prev" in
        --auth-type)
            COMPREPLY=($(compgen -W "basic bearer" -- "$cur"))
            return 0
            ;;
        --output-format|-o)
            # 根据上下文判断是 query 的 output-format 还是 export 的 output
            local in_query=false
            for word in "${words[@]}"; do
                case "$word" in
                    query|q) in_query=true; break ;;
                esac
            done
            if $in_query; then
                COMPREPLY=($(compgen -W "table json csv graph" -- "$cur"))
            else
                # export -o 是文件路径
                COMPREPLY=($(compgen -f -- "$cur"))
            fi
            return 0
            ;;
        --config|-c|--output|--input|-i|--tls-ca|--tls-cert|--tls-key)
            # 文件路径补全
            COMPREPLY=($(compgen -f -- "$cur"))
            return 0
            ;;
        --server-url)
            COMPREPLY=($(compgen -W "http://localhost:8428 http://localhost:9090" -- "$cur"))
            return 0
            ;;
    esac

    # 确定当前上下文
    local cmd="" subcmd=""
    local i
    for ((i=1; i<cword; i++)); do
        case "${words[$i]}" in
            -*)
                # 跳过 flags
                # 检查是否是需要值的 flag，如果是则跳过下一个参数
                case "${words[$i]}" in
                    --config|-c|--server-url|--server-path-prefix|--server-timeout|\
                    --auth-type|--auth-user|--auth-password|--auth-token|\
                    --tls-ca|--tls-cert|--tls-key|--output-format|-o|--output|--input|-i|\
                    --time|--range|--step|--start|--end|--max-rows-per-line|--csv-format|\
                    --job|--instance)
                        ((i++))
                        ;;
                esac
                ;;
            *)
                if [[ -z "$cmd" ]]; then
                    cmd="${words[$i]}"
                elif [[ -z "$subcmd" ]]; then
                    subcmd="${words[$i]}"
                fi
                ;;
        esac
    done

    # 如果当前词以 - 开头，补全 flags
    if [[ "$cur" == -* ]]; then
        local flags="$global_flags"
        case "$cmd" in
            query|q)
                flags="$global_flags $query_flags"
                ;;
            export|e)
                flags="$global_flags $export_flags"
                case "$subcmd" in
                    json) flags="$flags $export_json_flags" ;;
                    csv) flags="$flags $export_csv_flags" ;;
                esac
                ;;
            import|i)
                flags="$global_flags $import_flags"
                case "$subcmd" in
                    prometheus) flags="$flags $import_prometheus_flags" ;;
                esac
                ;;
        esac
        COMPREPLY=($(compgen -W "$flags" -- "$cur"))
        return 0
    fi

    # 补全命令
    case "$cmd" in
        "")
            COMPREPLY=($(compgen -W "$main_commands" -- "$cur"))
            ;;
        query|q)
            if [[ -z "$subcmd" ]]; then
                COMPREPLY=($(compgen -W "$query_commands" -- "$cur"))
            fi
            ;;
        export|e)
            if [[ -z "$subcmd" ]]; then
                COMPREPLY=($(compgen -W "$export_commands" -- "$cur"))
            fi
            ;;
        import|i)
            if [[ -z "$subcmd" ]]; then
                COMPREPLY=($(compgen -W "$import_commands" -- "$cur"))
            fi
            ;;
        completion)
            if [[ -z "$subcmd" ]]; then
                COMPREPLY=($(compgen -W "$completion_commands" -- "$cur"))
            fi
            ;;
    esac

    return 0
}

complete -o default -F _mc_metrics_completions mc-metrics
`
	_, err := io.WriteString(w, script)
	return err
}
