package completion

import (
	"io"
)

func generateZshCompletion(w io.Writer) error {
	script := `#compdef mc-metrics

# mc-metrics zsh completion script
# Generated by: mc-metrics completion zsh

_mc_metrics() {
    local curcontext="$curcontext" state line
    typeset -A opt_args

    local -a global_flags
    global_flags=(
        '(-c --config)'{-c,--config}'[配置文件路径]:config file:_files'
        '--server-url[VictoriaMetrics 服务器地址]:url:(http://localhost:8428 http://localhost:9090)'
        '--server-path-prefix[API 路径前缀]:prefix:'
        '--server-timeout[请求超时时间]:duration:'
        '--auth-type[认证类型]:auth type:(basic bearer)'
        '--auth-user[Basic 认证用户名]:username:'
        '--auth-password[Basic 认证密码]:password:'
        '--auth-token[Bearer Token]:token:'
        '--tls-ca[CA 证书路径]:ca file:_files'
        '--tls-cert[客户端证书路径]:cert file:_files'
        '--tls-key[客户端密钥路径]:key file:_files'
        '--tls-skip-verify[跳过证书验证]'
        '(- *)'{-h,--help}'[显示帮助信息]'
    )

    _arguments -C \
        $global_flags \
        '1: :_mc_metrics_commands' \
        '*::arg:->args'

    case $state in
        args)
            case $line[1] in
                query|q)
                    _mc_metrics_query
                    ;;
                export|e)
                    _mc_metrics_export
                    ;;
                import|i)
                    _mc_metrics_import
                    ;;
                completion)
                    _mc_metrics_completion
                    ;;
            esac
            ;;
    esac
}

_mc_metrics_commands() {
    local -a commands
    commands=(
        'query:执行 MetricsQL 查询'
        'q:执行 MetricsQL 查询 (别名)'
        'export:导出时序数据'
        'e:导出时序数据 (别名)'
        'import:导入时序数据'
        'i:导入时序数据 (别名)'
        'version:显示版本信息'
        'completion:生成 shell 补全脚本'
        'help:显示帮助信息'
    )
    _describe -t commands 'mc-metrics commands' commands
}

_mc_metrics_query() {
    local curcontext="$curcontext" state line
    typeset -A opt_args

    local -a query_flags
    query_flags=(
        '(-o --output-format)'{-o,--output-format}'[输出格式]:format:(table json csv graph)'
        '--output-no-headers[禁用表头输出]'
        '--time[查询时间点]:time:'
        '--range[范围查询的时间跨度]:duration:'
        '--step[范围查询的步长]:duration:'
    )

    _arguments -C \
        $query_flags \
        '1: :_mc_metrics_query_commands' \
        '*::arg:->args'

    case $state in
        args)
            case $line[1] in
                metrics|labels|label-values|series)
                    # 这些子命令接受参数但不需要特殊补全
                    ;;
            esac
            ;;
    esac
}

_mc_metrics_query_commands() {
    local -a commands
    commands=(
        'metrics:列出所有指标名称'
        'labels:列出所有标签名称'
        'label-values:获取指定标签的所有值'
        'series:列出匹配的时间序列'
        'version:显示版本信息'
    )
    _describe -t commands 'query subcommands' commands
}

_mc_metrics_export() {
    local curcontext="$curcontext" state line
    typeset -A opt_args

    local -a export_flags
    export_flags=(
        '--start[开始时间]:time:'
        '--end[结束时间]:time:'
        '(-o --output)'{-o,--output}'[输出文件路径]:output file:_files'
        '--gzip[启用 gzip 压缩输出]'
    )

    _arguments -C \
        $export_flags \
        '1: :_mc_metrics_export_commands' \
        '*::arg:->args'

    case $state in
        args)
            case $line[1] in
                json)
                    _arguments \
                        '--max-rows-per-line[每行最大样本数]:count:'
                    ;;
                csv)
                    _arguments \
                        '--csv-format[CSV 列定义]:format:' \
                        '--reduce-mem-usage[跳过去重以减少内存使用]'
                    ;;
            esac
            ;;
    esac
}

_mc_metrics_export_commands() {
    local -a commands
    commands=(
        'json:导出 JSON Line 格式'
        'csv:导出 CSV 格式'
        'native:导出 Native 二进制格式'
        'version:显示版本信息'
    )
    _describe -t commands 'export subcommands' commands
}

_mc_metrics_import() {
    local curcontext="$curcontext" state line
    typeset -A opt_args

    local -a import_flags
    import_flags=(
        '(-i --input)'{-i,--input}'[输入文件路径]:input file:_files'
        '--gzip[输入为 gzip 压缩格式]'
    )

    _arguments -C \
        $import_flags \
        '1: :_mc_metrics_import_commands' \
        '*::arg:->args'

    case $state in
        args)
            case $line[1] in
                prometheus)
                    _arguments \
                        '--job[Pushgateway job 标签]:job:' \
                        '--instance[Pushgateway instance 标签]:instance:'
                    ;;
            esac
            ;;
    esac
}

_mc_metrics_import_commands() {
    local -a commands
    commands=(
        'json:导入 JSON Line 格式'
        'csv:导入 CSV 格式'
        'native:导入 Native 二进制格式'
        'prometheus:导入 Prometheus exposition 格式'
        'version:显示版本信息'
    )
    _describe -t commands 'import subcommands' commands
}

_mc_metrics_completion() {
    local -a commands
    commands=(
        'bash:生成 bash 补全脚本'
        'zsh:生成 zsh 补全脚本'
    )
    _describe -t commands 'completion subcommands' commands
}

# 如果未定义则加载补全
if [[ -z "${_comps[mc-metrics]}" ]]; then
    compdef _mc_metrics mc-metrics
fi
`
	_, err := io.WriteString(w, script)
	return err
}
